# Generated by Django 5.1.4 on 2025-01-08 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('Modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('Anio', models.CharField(max_length=4, verbose_name='Año')),
                ('Placa', models.CharField(max_length=7, verbose_name='Placa')),
                ('Disponibilidad', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('User', models.CharField(max_length=100, verbose_name='User')),
                ('Contrasena', models.CharField(max_length=30, verbose_name='Contraseña')),
                ('NombresApellidos', models.CharField(max_length=100, verbose_name='Nombres y Apellidos')),
                ('Cargo', models.CharField(max_length=30, verbose_name='Cargo')),
                ('Email', models.CharField(max_length=100, verbose_name='Email')),
                ('Telefono', models.CharField(max_length=11, verbose_name='Teléfono')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='Nombre de usuario')),
                ('password', models.CharField(max_length=30, verbose_name='Contraseña')),
                ('Nombres', models.CharField(max_length=100)),
                ('Apellidos', models.CharField(max_length=100)),
                ('DNI', models.CharField(max_length=8, unique=True)),
                ('Email', models.CharField(max_length=100, unique=True)),
                ('Telefono', models.CharField(max_length=11)),
                ('FechaNacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('Direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('NroLicencia', models.CharField(max_length=12, unique=True, verbose_name='Número de licencia')),
                ('FechaExpLicencia', models.DateField(verbose_name='Fecha de exp. de licencia')),
            ],
        ),
    ]
