# Generated by Django 5.1.3 on 2025-01-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Nombres',
            field=models.CharField(max_length=100, verbose_name='Nombres completos'),
        ),
    ]
